// Static synthetic example shared with the V2 scheduled prompt; no user data.
export const DAILY_DIGEST_MARKDOWN_CONTRACT = {
  schemaVersion: 'daily-digest.v1',
  contractVersion: '2026-09-14.2',
  instructions: [
    'Replace all example content, dates and URLs. Preserve exact headings, full-width colons and field order. Do not wrap the Markdown in a code fence.',
    'The first two lines must be # Daily Digest and <!-- daily-digest.v1 --> with no blank line between them.',
    'Theme: 8–90 characters; glance: 3–5 numbered lines, each 8–90; lead stories: 1–2; headline: 4–100; source: 0–60; time: 0–40.',
    'Lead content: whatHappened and whyItMatters 20–260, whatToWatch 12–220. Each exact bilingual heading must be followed by 内容：.',
    'Categories: 1–6, names 2–40; each has 1–6 items with 摘要：8–120. 金融与市场 and 观察名单 are ### categories inside ## Category Digest, not standalone ## sections.',
    'Mail Briefing: 0–20 items, title 4–100, source/time 0–60, summary 8–220, why 8–180, action 4–140, due 0–40. Use 需要采取的措施：无需立即行动 and 截止：— when appropriate.',
    'Mail Tasks: 0–20 items, title 4–100, source 0–60, due 0–40, detail 8–220. Worth Your Time: 0–3, title 4–100, source 0–60, valid HTTP(S) link, note 4–90.',
    'Mail Briefing, Mail Tasks and Worth Your Time may have no items when the inputs permit; keep their headings. Follow requirements for actual input coverage, ordinary news counts, sources and categories.',
    'Source logos may be omitted; if supplied they must already be hosted. Images may be empty or HTTP(S) URLs or hosted paths. Never invent news, dates, links or images to satisfy the example.',
    'On INVALID_DIGEST_FORMAT, fix validationIssues paths and repeat dry-run with the full corrected document. A failed validation does not publish or enqueue mail.',
  ],
  markdownTemplate: [
    "# Daily Digest",
    "<!-- daily-digest.v1 -->",
    "## Today at a Glance",
    "1. 第一条概览说明当天经过核实的重要变化。",
    "2. 第二条概览概括市场与关注名单的信息边界。",
    "3. 第三条概览提醒查看邮件摘要及必要行动。",
    "日期：2026-09-13",
    "今日主题：完整日报同时覆盖新闻邮件与市场观察",
    "## Lead Story",
    "### 示例重点新闻标题",
    "来源：Example News A",
    "时间：2026-09-13",
    "链接：https://example.com/news/lead",
    "图片：https://example.com/images/lead.jpg",
    "#### What happened / 发生了什么",
    "内容：这是用于验证正文结构的示例事实描述，实际运行时必须替换为公开来源已经核实的新闻事实。",
    "#### Why it matters / 为什么重要",
    "内容：这是用于验证正文结构的示例影响说明，实际运行时应解释变化影响哪些主体及其成立条件。",
    "#### What to watch / 接下来关注什么",
    "内容：继续核对后续公开数据以及相关机构发布的进展信息。",
    "## Category Digest",
    "### 科技与产品",
    "#### 示例科技新闻第一条",
    "来源：Example News B",
    "时间：2026-09-13",
    "链接：https://example.com/news/technology-one",
    "图片：https://example.com/images/technology-one.jpg",
    "摘要：这是第一条科技新闻的示例摘要，实际运行时替换为经过核实的内容。",
    "#### 示例科技新闻第二条",
    "来源：Example News C",
    "时间：2026-09-13",
    "链接：https://example.com/news/technology-two",
    "图片：https://example.com/images/technology-two.jpg",
    "摘要：这是第二条科技新闻的示例摘要，不能与第一条重复选题。",
    "### 政策与监管",
    "#### 示例政策新闻标题",
    "来源：Example News A",
    "时间：2026-09-13",
    "链接：https://example.com/news/policy",
    "图片：",
    "摘要：这是政策新闻的示例摘要，实际运行时需要引用真实公开信息。",
    "### 科学与社会",
    "#### 示例科学新闻标题",
    "来源：Example News C",
    "时间：2026-09-13",
    "链接：https://example.com/news/science",
    "图片：",
    "摘要：这是科学新闻的示例摘要，实际运行时需要说明事实与影响。",
    "### 金融与市场",
    "#### 示例市场数据快照",
    "来源：Yahoo Finance chart",
    "时间：最近交易日，实际运行时替换",
    "链接：",
    "图片：",
    "摘要：示例市场数据需替换为真实行情、交易日和时区；休市时不得编造当日报价。",
    "### 观察名单",
    "#### 示例关注股票甲与乙",
    "来源：Yahoo Finance chart",
    "时间：最近可核实日期，实际运行时替换",
    "链接：",
    "图片：",
    "摘要：DEMOA 与 DEMOB 是格式示例代码；实际运行逐项替换为关注股票及有证据的 Thesis 状态。",
    "## Mail Briefing",
    "### 示例邮件简报第一封",
    "来源：示例发件机构甲",
    "时间：2026-09-13",
    "摘要：第一封邮件的示例摘要说明来信内容，实际运行时必须依据 MCP 返回的摘要。",
    "为什么值得看：这封邮件的示例价值说明需要替换为与用户有关的实际信息。",
    "需要采取的措施：无需立即行动",
    "截止：—",
    "### 示例邮件简报第二封",
    "来源：示例发件机构乙",
    "时间：2026-09-13",
    "摘要：第二封邮件的示例摘要需要独立覆盖另一封来信，不能用第一封的内容复制凑数。",
    "为什么值得看：这封邮件的示例价值说明用于解释需要了解或处理的原因。",
    "需要采取的措施：核对后按来信要求回复",
    "截止：—",
    "## Mail Tasks",
    "### 示例邮件明确行动",
    "来源：示例发件机构乙",
    "截止：—",
    "详情：这里只列邮件明确要求的动作，实际无动作时删掉本条并说明无需立即行动。",
    "## Worth Your Time",
    "## Footer",
    "由日报 V2 自动整理；数据仅供参考。",
  ].join('\n'),
} as const;
