// Compatibility facade: callers retain the same API; queries never import this file.
import { initDb } from './database/connection.js';
export { initDb, assertNoUnreconciledChatWal, exportChatDb } from './database/connection.js';
export type { DbSession, DbMessage, DbAiScheduleMessage, DbUser, DbInviteCode, DbEmailCode, DbReminder, DbUserApiKey, DbDailyReportToken, DbDailyReportCloudContext, DbDailyReportCloudActivity, DbDailyReportMediaBatchStatus, DbDailyReportMediaBatch, DbDailyReportMediaAssetStatus, DbDailyReportMediaAsset, DbOAuthClient, DbOAuthAuthorizationRequest, DbOAuthAuthorizationCode, DbOAuthAccessToken, DbOAuthRefreshToken, DbUserMailAccount, DbNoteItem, DbLibraryEntry, DbLibrarySort, DbLibraryPreference, DbLibraryEntryVersion, DbLibraryComment, DbLibraryPublishToken, DbLibraryListFilters, LibraryLifecycleAction, LibraryLifecycleResult } from './database/types.js';
export { getAllSessions, getSession, createSession, updateSession, deleteSession, getMessagesBySession, createMessage, updateMessage, deleteMessage, createMessages, getAiScheduleMessages, createAiScheduleMessage, updateAiScheduleMessage, deleteAiScheduleMessage, deleteExpiredAiScheduleMessages, clearAllData } from './database/queries/sessions.js';
export { getAllUsers, getUsersPaginated, getUserByEmail, getUserById, createUser, updateUserRole, updateUserDisabled, updateUserAdminApiSharing, updateUserLastLogin, getInviteCode, listInviteCodes, upsertInviteCode, getUserPreferredModel, updateUserPreferredModel, createEmailCode, verifyEmailCode, deleteEmailCode } from './database/queries/accounts.js';
export { getReminder, upsertReminder, exportUserAccountData, getAllEnabledReminders, getReminderEmail } from './database/queries/preferences.js';
export { getNoteItem, listNoteItems, searchNoteItems, createNoteItem, updateNoteItem, commitNoteOptimization, revertNoteOptimization, mergeNoteItems, deleteNoteItem, exportUserNoteItems, restoreUserNoteItems } from './database/queries/notes.js';
export { getLibraryPreference, upsertLibraryPreference, getLibraryEntry, getLibraryEntryBySourceId, listLibraryEntries, createLibraryEntry, updateLibraryEntry, deleteLibraryEntry, applyLibraryLifecycle, createLibraryEntryVersion, listLibraryEntryVersions, listLibraryComments, createLibraryComment, deleteLibraryComment, getLibraryPublishToken, replaceLibraryPublishToken, revokeLibraryPublishToken, findActiveLibraryPublishTokenByHash, markLibraryPublishTokenUsed, exportUserLibraryEntries, restoreUserLibraryEntries } from './database/queries/library.js';
export { getUserApiKey, getAdminSharedApiKey, upsertUserApiKey, deleteUserApiKey, getUserMailAccount, upsertUserMailAccount, deleteUserMailAccount } from './database/queries/credentials.js';
export { getDailyReportToken, replaceDailyReportToken, revokeDailyReportToken, findActiveDailyReportTokenByHash, markDailyReportTokenUsed } from './database/queries/report-tokens.js';
export { getDailyReportCloudContext, upsertDailyReportCloudContext, listDailyReportCloudActivity, createDailyReportCloudActivity, createDailyReportMediaBatch, getDailyReportMediaBatch, listDailyReportMediaBatches, updateDailyReportMediaBatchStatus, getDailyReportMediaAsset, listDailyReportMediaAssets, upsertDailyReportMediaAsset, deleteDailyReportCloudData } from './database/queries/report-cloud.js';
export { createOAuthClient, getOAuthClient, createOAuthAuthorizationRequest, getOAuthAuthorizationRequest, setOAuthAuthorizationRequestUser, setOAuthAuthorizationRequestScope, deleteOAuthAuthorizationRequest, createOAuthAuthorizationCode, getOAuthAuthorizationCode, markOAuthAuthorizationCodeUsed, createOAuthAccessToken, getActiveOAuthAccessToken, markOAuthAccessTokenUsed, revokeOAuthAccessToken, createOAuthRefreshToken, getActiveOAuthRefreshToken, getActiveOAuthRefreshTokenForClientUser, getOAuthRefreshToken, markOAuthRefreshTokenUsed, revokeOAuthRefreshFamily, revokeOAuthRefreshToken, deleteOAuthUserData } from './database/queries/oauth.js';
export { deleteUser, clearUserData } from './database/queries/maintenance.js';
export { getOperationResult, saveOperationResult, deleteUserOperationResults } from './database/queries/operations.js';

export default { initDb };
