import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
const root = fs.mkdtempSync(path.join(os.tmpdir(), 'aicalendar-phase3-api-'));
process.env.DATA_DIR = root;
process.env.NODE_ENV = 'test';
process.env.APP_ENV = 'development';
process.env.BACKGROUND_JOBS_ENABLED = 'false';
process.env.BACKUP_ENCRYPTION_KEY = 'synthetic-backup-key';
const api = await import('./index.js');
await api.initializeServer();
const db = await import('./db.js');
const activity = await import('./activity-store.js');
const schedules = await import('./schedule-store.js');
const stamp = new Date().toISOString();
const users = ['owner', 'other'].map(id => db.createUser({ id, email: id + '@example.invalid', password_hash: 'synthetic', role: 'user', disabled: 0, created_at: stamp, updated_at: stamp }));
test('import confirmation is durable, account scoped and safe to retry after receipt failure', async t => {
  const listener = api.app.listen(0, '127.0.0.1');
  await new Promise<void>(resolve => listener.once('listening', resolve));
  const base = 'http://127.0.0.1:' + (listener.address() as { port: number }).port;
  const request = (id: string, user = 0) => fetch(base + '/api/ai/imports/' + id + '/confirm', { method: 'POST', headers: { Authorization: 'Bearer ' + api.signUserToken(users[user]), 'Content-Type': 'application/json' }, body: JSON.stringify({}) });
  try {
    const draft = activity.createAiImport({ userId: 'owner', sourceType: 'text', inputText: 'synthetic', draft: { kind: 'once', title: 'retry import', dueDate: '2026-12-25', reminderOffsets: [] } });
    assert.equal((await request(draft.id, 1)).status, 404);
    let failed = false;
    const rename = fs.renameSync;
    const mock = t.mock.method(fs, 'renameSync', (from: fs.PathLike, to: fs.PathLike) => { if (!failed && String(to) === path.join(root, 'chat.db')) { failed = true; throw new Error('injected receipt failure'); } return rename(from, to); });
    assert.equal((await request(draft.id)).status, 400);
    mock.mock.restore();
    assert.equal(activity.getAiImport(draft.id, 'owner')?.status, 'draft');
    assert.equal(schedules.getAllSchedules('owner').length, 0);
    const first = await request(draft.id); assert.equal(first.status, 200); const result = await first.json();
    await db.initDb(); await activity.initActivityDb(); await schedules.initScheduleDb();
    const second = await request(draft.id); assert.equal(second.status, 200); assert.deepEqual(await second.json(), result);
    assert.equal(schedules.getAllSchedules('owner').length, 1);
    assert.equal((await request(draft.id, 1)).status, 404);

    const planId = 'synthetic-replay-plan';
    db.createAiScheduleMessage({ id: 'synthetic-history', user_id: 'owner', role: 'assistant', type: 'plan', content: 'pending', intent: 'create', schedule_items: null, created_at: new Date().toISOString(), plan: JSON.stringify({ id: planId, expiresAt: new Date(Date.now() + 3600000).toISOString(), rawOperations: [{ type: 'create', data: { title: 'plan schedule', type: 'todo', start_time: '2026-12-25T09:00:00' } }, { type: 'update', scheduleId: 'missing-target', data: { title: 'must fail' } }], targetCalendarId: 'personal', today: '2026-12-25' }) });
    const auth = { Authorization: 'Bearer ' + api.signUserToken(users[0]), 'Content-Type': 'application/json' };
    await fetch(base + '/api/ai-schedule/history', { headers: auth });
    const confirmPlan = () => fetch(base + '/api/ai-chat/confirm', { method: 'POST', headers: auth, body: JSON.stringify({ planId }) });
    let receiptFailed = false;
    const planMock = t.mock.method(fs, 'renameSync', (from: fs.PathLike, to: fs.PathLike) => { if (!receiptFailed && String(to) === path.join(root, 'chat.db')) { receiptFailed = true; throw new Error('plan receipt failure'); } return rename(from, to); });
    assert.equal((await confirmPlan()).status, 500);
    planMock.mock.restore();
    assert.equal(schedules.getAllSchedules('owner').length, 1);
    const planResponse = await confirmPlan(); assert.equal(planResponse.status, 200); const planResult = await planResponse.json();
    assert.equal(planResult.partial, true); assert.equal(planResult.changedDetails.created.length, 1); assert.equal(planResult.changedDetails.failures.length, 1);
    await db.initDb(); await schedules.initScheduleDb();
    assert.deepEqual(await (await confirmPlan()).json(), planResult);
    assert.equal(schedules.getAllSchedules('owner').length, 2);

    const completedId = result.created.id;
    const completeSchedule = () => fetch(base + '/api/completions', { method: 'POST', headers: auth, body: JSON.stringify({ sourceType: 'schedule', sourceId: completedId }) });
    assert.equal((await completeSchedule()).status, 200);
    assert.equal((await completeSchedule()).status, 200);
    assert.equal(activity.listCompletions('owner', { sourceId: completedId }).length, 1);
    const reminders = await import('./reminder-store.js');
    const task = reminders.createReminderTask({ userId: 'owner', type: 'generic', name: 'recurring completion', config: { templateKey: 'custom', rule: { frequency: 'interval', anchorDate: '2026-12-25', interval: 1, unit: 'month', advancePolicy: 'calendar' }, reminderOffsets: [0], reminderTime: '09:00', actionGuide: '', priority: 'medium' } });
    const cycleId = task.currentCycle!.id;
    const completeCycle = () => fetch(base + '/api/cycle-reminders/' + task.id + '/complete', { method: 'POST', headers: auth, body: JSON.stringify({ cycleId, completedDate: '2026-12-25' }) });
    let cycleFailed = false;
    const cycleMock = t.mock.method(fs, 'renameSync', (from: fs.PathLike, to: fs.PathLike) => { if (!cycleFailed && String(to) === path.join(root, 'activity.db')) { cycleFailed = true; throw new Error('cycle proof failure'); } return rename(from, to); });
    assert.equal((await completeCycle()).status, 400);
    cycleMock.mock.restore();
    assert.notEqual(reminders.getReminderHistory(task.id, 'owner').find(cycle => cycle.id === cycleId)?.status, 'completed');
    assert.equal((await completeCycle()).status, 200); assert.equal((await completeCycle()).status, 200);
    assert.equal(activity.listCompletions('owner', { sourceId: task.id }).length, 1);
    assert.equal(reminders.getReminderHistory(task.id, 'owner').length, 2);
  } finally { listener.closeAllConnections(); await new Promise<void>(resolve => listener.close(() => resolve())); }
});
